name: demo_app_new
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  octo_image: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  # flutter_circular_chart: ^0.1.0
  video_player: ^2.9.2
  # flutter_slidable: ^3.1.2
  analog_clock: ^0.1.1
  charts_flutter: ^0.12.0
  convex_bottom_bar: ^3.2.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_hooks: ^0.20.5
  http: ^1.1.0
  cached_network_image: ^3.2.0
  flutter_neumorphic: ^3.1.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  flutter_local_notifications: ^18.0.1
  flutter_microsoft_clarity: ^0.0.1
  # flutter_uxcam: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

  uses-material-design: true
  assets:
    - assets/dummy_logo.png
    - assets/video.mp4
    - assets/image.png
    - assets/profile.jpg
    - assets/login.png
